version: '2'
services:
  config01:
    image: mongo:3.6
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config02:
    image: mongo:3.6
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  config03:
    image: mongo:3.6
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01a:
    image: mongo:3.6
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard01b:
    image: mongo:3.6
    command: mongod --port 27018 --shardsvr --replSet shard01 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02a:
    image: mongo:3.6
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard02b:
    image: mongo:3.6
    command: mongod --port 27019 --shardsvr --replSet shard02 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard03a:
    image: mongo:3.6
    command: mongod --port 27020 --shardsvr --replSet shard03 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  shard03b:
    image: mongo:3.6
    command: mongod --port 27020 --shardsvr --replSet shard03 --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./scripts:/scripts
  router01:
    image: mongo:3.6
    command: mongos --port 27017 --bind_ip_all --configdb configserver/config01:27017,config02:27017,config03:27017
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
  router02:
    image: mongo:3.6
    command: mongos --port 27017 --bind_ip_all --configdb configserver/config01:27017,config02:27017,config03:27017
    ports:
      - "27018:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
  router03:
    image: mongo:3.6
    command: mongos --port 27017 --bind_ip_all --configdb configserver/config01:27017,config02:27017,config03:27017
    ports:
      - "27019:27017"
    volumes:
      - ./scripts:/scripts
    depends_on:
      - config01
      - config02
      - config03
      - shard01a
      - shard01b
      - shard02a
      - shard02b
      - shard03a
      - shard03b
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - "1234:1234"
    depends_on:
      - router01
      - router02
      - router03
